# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FumeBotAbout_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(560, 400)
        AboutDialog.setMinimumSize(QtCore.QSize(560, 400))
        AboutDialog.setMaximumSize(QtCore.QSize(560, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/bot_icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AboutDialog.setWindowIcon(icon)
        AboutDialog.setAutoFillBackground(False)
        AboutDialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(AboutDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.whole_verticalLayout = QtWidgets.QVBoxLayout()
        self.whole_verticalLayout.setObjectName("whole_verticalLayout")
        self.image_horizontalLayout = QtWidgets.QHBoxLayout()
        self.image_horizontalLayout.setObjectName("image_horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.image_horizontalLayout.addItem(spacerItem)
        self.about_image_label = QtWidgets.QLabel(AboutDialog)
        self.about_image_label.setMaximumSize(QtCore.QSize(360, 240))
        self.about_image_label.setText("")
        self.about_image_label.setPixmap(QtGui.QPixmap(":/Images/about_image.jpg"))
        self.about_image_label.setScaledContents(True)
        self.about_image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.about_image_label.setObjectName("about_image_label")
        self.image_horizontalLayout.addWidget(self.about_image_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.image_horizontalLayout.addItem(spacerItem1)
        self.whole_verticalLayout.addLayout(self.image_horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.whole_verticalLayout.addItem(spacerItem2)
        self.aboutlabel = QtWidgets.QLabel(AboutDialog)
        self.aboutlabel.setObjectName("aboutlabel")
        self.whole_verticalLayout.addWidget(self.aboutlabel)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.whole_verticalLayout.addItem(spacerItem3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.buttonBox = QtWidgets.QDialogButtonBox(AboutDialog)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.whole_verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.whole_verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(AboutDialog)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About"))
        self.aboutlabel.setText(_translate("AboutDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">This application is used for controlling FumeBot an Arduino and</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Raspberry Pi based robot.</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Copyright © 2018 Ajith Thomas. All Rights Reserved.</span></p></body></html>"))
from . import FumeBotImages_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AboutDialog = QtWidgets.QDialog()
    ui = Ui_AboutDialog()
    ui.setupUi(AboutDialog)
    AboutDialog.show()
    sys.exit(app.exec_())
